### PR TITLE
Bump rack from 1.5.2 to 1.6.3

### PR DESCRIPTION
**Pull request by christianblais**
Bump rack from 1.5.2 to 1.6.3

@j-mutter @fw42 

Browser tests are still working when pointing to this branch. I'll try a Shopify branch that points to this SHA, let's see if we get a green CI.

screen shot 2015-06-18 at 4 30 17 pm

### CODE REVIEW

**Comment by christianblais** [comment]
https://github.com/Shopify/shopify/pull/47561

**Comment by j-mutter** [comment]
:+1:

**Comment by j-mutter** [comment]
(assuming Shopify tests work)

**Comment by christianblais** [comment]
Tests are green. I'll merge tomorrow.

**Comment by christianblais** [comment]
@EiNSTeiN- mind to cover for @fw42 ?

**Pull request merged**
